# Generated by Django 4.0.1 on 2022-01-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tovar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(blank=True, default='', max_length=6, verbose_name='KOD tovar*')),
                ('new', models.BooleanField(default=True, help_text='New?', verbose_name='New?')),
                ('top', models.BooleanField(default=False, help_text='Show main page', verbose_name='Top tovar')),
                ('title', models.CharField(db_index=True, max_length=40, verbose_name='Title*')),
                ('slug', models.SlugField(max_length=200, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Price*')),
                ('available', models.BooleanField(default=True, verbose_name='Active')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last edit')),
                ('image_main', models.ImageField(upload_to='media/products/%Y/%m/%d', verbose_name='Main photo*')),
            ],
            options={
                'verbose_name': 'Tovar',
                'verbose_name_plural': 'Tovars',
                'ordering': ('title',),
                'index_together': {('id', 'slug', 'top')},
            },
        ),
    ]
