# Generated by Django 4.0.1 on 2022-01-17 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar',
            name='image_main',
            field=models.ImageField(upload_to='Products/%Y:%m:%d/', verbose_name='Main photo*'),
        ),
    ]
