# Generated by Django 4.0.1 on 2022-01-17 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_alter_tovar_kod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar',
            name='kod',
            field=models.CharField(blank=True, db_index=True, default='', max_length=6, verbose_name='KOD tovar*'),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='price',
            field=models.FloatField(max_length=10, verbose_name='Price*'),
        ),
    ]
