# Generated by Django 4.0.1 on 2022-01-17 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_alter_tovar_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar',
            name='kod',
            field=models.CharField(blank=True, db_index=True, default='', max_length=6, unique=True, verbose_name='KOD tovar*'),
        ),
    ]
