# Generated by Django 4.0.1 on 2022-01-17 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_alter_tovar_kod'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifyForAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=40, verbose_name='Title')),
            ],
        ),
    ]
