# Generated by Django 4.0.1 on 2022-01-18 00:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_notifyforadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifyforadmin',
            name='desc',
            field=models.TextField(default=django.utils.timezone.now, max_length=200, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
