# Generated by Django 4.0.1 on 2022-01-18 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0009_notifyforadmin_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifyforadmin',
            options={'ordering': ('title',), 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.RenameField(
            model_name='notifyforadmin',
            old_name='desc',
            new_name='slug',
        ),
        migrations.AlterIndexTogether(
            name='notifyforadmin',
            index_together={('id', 'title')},
        ),
    ]
