# Generated by Django 4.0.1 on 2022-01-18 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0011_notifyforadmin_created_notifyforadmin_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar',
            name='kod',
            field=models.IntegerField(blank=True, db_index=True, default='', max_length=6, unique=True, verbose_name='KOD tovar*'),
        ),
    ]
