# Generated by Django 4.0.1 on 2022-01-18 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0012_alter_tovar_kod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar',
            name='kod',
            field=models.IntegerField(blank=True, db_index=True, default='', unique=True, verbose_name='KOD tovar*'),
        ),
    ]
